process.env.NEXT_PUBLIC_STELLAR_RPC_URL = 'https://soroban-testnet.stellar.org';
process.env.NEXT_PUBLIC_STELLAR_NETWORK_PASSPHRASE = 'Test SDF Network ; September 2015';
process.env.NEXT_PUBLIC_PLANET_CONTRACT = 'CCGFXO5TUAPYMUEPAPGYLOPCBRZLDJRLKVYDHQBLXUK37FJWTONQMPZD';
